name: MASTERMIND

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: mastermind
          - os: macos-latest
            artifact: mastermind
          - os: windows-latest
            artifact: Release/mastermind.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Installation de SDL (macOS)
        if: runner.os == 'macOS'
        run: brew install sdl3 sdl3_ttf

      - name: Installation de SDL3 (Windows)
        if: runner.os == 'Windows'
        uses: libsdl-org/setup-sdl@main
        with:
          version: 3-latest
      
      - name: Installation de SDL3 (Linux)
        if: runner.os == 'Linux'
        uses: libsdl-org/setup-sdl@main
        with:
          version: 3-latest
      
      - name: Installation de SDL3_ttf (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/libsdl-org/SDL_ttf.git
          cmake -B SDL_ttf/build -S SDL_ttf -DCMAKE_BUILD_TYPE=Release
          cmake --install SDL_ttf/build

      - name: Installation de SDL3_ttf (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype-dev libharfbuzz-dev
          git clone --depth 1 https://github.com/libsdl-org/SDL_ttf.git
          cmake -B SDL_ttf/build -S SDL_ttf -DCMAKE_BUILD_TYPE=Release
          sudo cmake --install SDL_ttf/build

      - name: Configuration
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Zip (Linux/macOS)
        if: runner.os != 'Windows'
        run: zip -r MASTERMIND-${{ runner.os }}.zip build/mastermind build/assets
      
      - name: Zip(Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path build/Release/mastermind.exe, build/assets -DestinationPath MASTERMIND-${{ runner.os }}.zip
      
      - name: Mise en ligne
        uses: actions/upload-artifact@v4
        with:
          name: mastermind-${{ runner.os }}
          path: |
              MASTERMIND-${{ runner.os }}.zip

  release:
    needs:
      - build
    
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Téléchargement
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mastermind-Windows/MASTERMIND-Windows.zip
            mastermind-macOS/MASTERMIND-macOS.zip
            mastermind-Linux/MASTERMIND-Linux.zip

